name: Trigger CLI Release
on:
  release:
    types: [ published ]
jobs:
  trigger-cli-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CLI_RELEASE_APP_ID }}
          private_key: ${{ secrets.CLI_RELEASE_PRIVATE_KEY }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: lgarber-akamai/linode-cli
          event-type: cli-release
          client-payload: '{"spec_version": "${{ github.event.release.tag_name }}"}'